export default {
  'zh-CN': {
    toDoList: {
      title: '待办事项',
    },
    email: {
      // title: '邮件统计',
      title: '我的邮件',
      failtoday: '今日失败数',
      failcount: '累计失败总数',
      weekcount: '本周发送总数',
    },
    sms: {
      title: '短信统计',
      failtoday: '今日失败数',
      failcount: '累计失败总数',
      weekcount: '本周发送总数',
      tiao: '条',
    },
    workno: {
      title: '员工号监控',
      empIdnum: '剩余员工号',
      postIdnum: '剩余职位号',
    },
    autotask: {
      title: '自动任务统计',
      count: '总任务数',
      countstat: '总任务数统计',
      validity: '生效任务数',
      invalid: '失效任务数',
      typestat: '任务类别统计',
      plstat: '任务执行频率统计',
    },
    autotaskrun: {
      title: '自动任务执行统计',
      title1: '任务运行统计',
      runfailure: '今日运行失败',
      runsuccess: '今日运行成功',
      startfailure: '今日启动失败',
      startsuccess: '今日启动成功',
    },
    calendarList: {
      title: '系统日历',
      view: '查看',
      moreMessage: '更多提醒',
      remindTitle: '提醒标题',
      remindType: '提醒范围',
      remindContent: '提醒内容',
      remindStatime: '生效日期',
      remindStoptime: '失效日期',
      remindNote: '备注',
      remindTitleDis: '请输入提醒标题...',
      remindTypeDis: '选择提醒范围',
      remindContentDis: '请输入提醒内容...',
      remindStatimeDis: '请选择生效日期',
      remindStoptimeDis: '请选择失效日期',
      remindHourtimeDis: '请选择时间',
      remindNoteDis: '请输入备注...',
      week: {
        mon: '星期一',
        tue: '星期二',
        wed: '星期三',
        thu: '星期四',
        fri: '星期五',
        sat: '星期六',
        sun: '星期日',
      },
    },
    quickMove: {
      title: '快捷操作',
      quickMoveOpr: '分配快捷操作',
      funLancodeDis: '功能节点名称',
      funCode: '功能节点编号',
      authFunImg: '图标',
      AssImg: '分配图片',
      pmtypeCodeDis: '请输入功能节点的名称',
      errReminder: '最多只能选择6个节点',
      set: '设置'
    },
    mailMsg: {
      title: '邮件信息',
      view: '查看',
      mailTime: '发送时间',
      mailObject: '主题',
      mailTo: '接收人',
      mailCc: '抄送人',
      mailStatus: '状态',
      mailContent: '邮件内容',
      mailError: '错误信息',
      mailDatasource: '数据来源',
      comment: '备注',
      mailTimeDis: '选择开始日期',
      mailEtimeDis: '选择结束日期',
      mailObjectDis: '请输入主题...',
      mailContentDis: '请输入邮件内容...',
      mailStatusDis: '请输入状态...',
    },
    question: {
      title: '咨询反馈',
      waitFeedback: '待反馈',
      dayAdd: '今日新增',
      dayDeal: '今日处理',
    },
    employee: {
      title: '业务分析',
      currentEmp: '当前员工',
      monenEmp: '当月入职',
      monlevEmp: '当月离职',
      monzhEmp: '当月转正',
      sexRate: '男女比例',
      man: '男',
      woman: '女',
      education: '学历',
      education1: '大专',
      education2: '本科',
      education3: '硕士',
      education4: '博士',
    },
    bookStore: {
      title: '知识库',
      tagTitle: '系统知识库',
      effectDate: '有效日期',
      back: '返回上级',
      attM: '附件',
      cmutKntypeName: '全部知识类型',
      keyWordsDis: '请输入知识库关键字...',
    },
    tools: {
      title: '小工具',
      TaxCal: '个税计算器',
      SocPolicy: '社保政策',
      OprBook: '操作手册',
      mostLink: '常用链接',
    },
    contentList: {
      title: '业务联系人',
      modaTitle: '业务支持',
      platSerConperson: '联系人',
      platSerTeam: '服务团队',
      platSerTime: '服务时间',
      platSerRange: '服务范围',
      platSerLevelName: '服务级别',
      platSerTel: '联系电话',
      platSerEmail: '电子邮箱',
    },
    messageList: {
      title: '消息通知',
      allMessage: '所有消息',
      unread: '未读消息',
      readed: '已读消息',
      noticbaseTitle: '标题',
      noticbaseSource: '类型',
      noticbasePublish: '日期',
      backTitle: '返回上级',
      attM: '附件',
    },
    menuItem: {
      iquestion: '我要咨询',
      businessupport: '业务支持',
      platsetting: '个性化设置',     
      skinpeeler:'皮肤风格',
    },
    platSetting: {
      title: '个性化设置',
      platApvset: '我的审批设置',
      apMethod: '设置同一业务审批中多个步骤参与时的审批方式',
      apMethodDis: '请选择审批设置方式',
      setSuccess: '设置成功',
      noEmpleeRemind: '当前用户未绑定员工,请先绑定员工!',
      grid: '九宫格显示方式'
    },
    new: {
      man: '男',
      wo: '女',
      total: '员工总数',
      more: '更多',
      peo: '人',
      news: '通知公告',
      laws: '政策制度',
      sign: '今日签到',
      leave: '今日请假',
      over: '今日加班',
      trip: '今日出差'
    },
    task: {
      mine: '我的任务',
      all: '全部任务',
      add: '添加任务'
    },
    msg: {
      show: '信息公示',
      det: '详情',
      date: '发布日期',
      inner: '详细内容',
    },
    order: {
      mine: '我的工单',
      back: '待反馈',
      new: '今日新增',
      dis: '今日处理',
      no: '工单编号',
      type: '工单类型',
      peo: '提交人',
    },
    attendance:{
      title: '当日考勤',
      sign: '当日签到',
      leave: '当日请假',
      Business: '当日出差',
    },
    Staff:{
      title: '员工异动',
      tmonth: '本月入职',
      member: '本月转正',
      renew: '本月续签',
      mobilize: '本月调动',
      departure:'本月离职'
    },
    Statistics:{
      title: '用户统计',
      userNumber: '用户总数',
      Currently: '当前生效',
      effective: '待生效',
      newToday: '今日新增',
      currentFailure :'当前失效'
    },
    Employee:{
      title: '员工分析',
      Gender: '性别分析',
      Compilation: '编制分析',
      Age: '司龄分析',
      Education: '学历分析',
    },
    myMessage:{
      title:'我的信息',
      empTip:'基本信息',
      empNumber:'工号',
      empName:'姓名',
      empStatus:'员工状态',
      empCompany:'公司',
      empDepart:'部门',
      empPost:'岗位',
      empPLeve:'职位级别',
      empEntime:'入职时间',
      empSiling:'司龄',
      empTjobtime:'参加工作时间',
      whetherRemote:'是否享受异地派遣福利',
      whetherForeign:'是否享受异地引进福利',
      officeMessage:'任职信息',
      contractMessage:'合同信息',
      bankMessage:'银行信息',
      qualificaMessage:'学历信息',
      trackRecord:'工作履历',
      contactMessage:'联系信息',
      addressMessage:'地址信息',
      familyMessage:'家庭信息',
    },
    skinpeelers:{
      current:'当前使用',
      immediately:'立即换肤',
      classic:'经典风格',
      black: '黑色风格',
      blue:'蓝色风格',
      green:'绿色风格',
      Navyblue:'藏青风格',
      red: '红色风格',
      Deeppurple: '深紫风格'
    },
    attendanceData:{
      title:'考勤数据',
      clock:'考勤打卡记录',
      replacement:'员工补卡申请',
    },
    Personnel:{
      title:'人事事务办理',
      self:'转正述职与自评',
      information:'调动信息确认',
      Renewal:'续签信息确认',
      resignation:'离职信息确认',
    },
    Holiday:{
      title:'假勤管理',
      Leave:'请假申请',
      business:'出差申请',
      cancellation:'销假申请',
      trip:'出差变更',
      revoke:'出差撤销'
    }
  },
  'en-US': {
    new: {
      man: 'BOY',
      wo: 'GIRL',
      total: 'Total Employees',
      more: 'More',
      peo: 'P',
      news: 'The notice',
      laws: 'Policies and systems',
      sign: 'Sign in today',
      leave: 'Ask for leave today',
      over: 'Work overtime today',
      trip: 'Go on business today'
    },
    task: {
      mine: 'My Tasks',
      all: 'All Tasks',
      add: 'Add Task'
    },
    msg: {
      show: 'Information Announcement',
      det: 'Details',
      date: 'Release Date',
      inner: 'Detail',
    },
    order: {
      mine: 'My Work Order',
      back: 'To feedback',
      new: 'Todays new',
      dis: 'To deal with today',
      no: 'Work order number',
      type: 'Work order type',
      peo: 'Submitter',
    },
    toDoList: {
      title: 'To-do items',
    },
    calendarList: {
      title: 'Message Reminder',
      view: 'Look Over',
      moreMessage: 'More Reminders',
      remindTitle: 'Reminder Title',
      remindType: 'Reminder Scope',
      remindContent: 'Reminder Content',
      remindStatime: 'Start Date',
      remindStoptime: 'End Date',
      remindNote: 'Comment',
      remindTitleDis: 'Please enter a reminder title...',
      remindTypeDis: 'Select reminder scope',
      remindContentDis: 'Please enter reminder content...',
      remindStatimeDis: 'Please select start date',
      remindStoptimeDis: 'Please select end date',
      remindHourtimeDis: 'Please select time',
      remindNoteDis: 'Please enter comment...',
      week: {
        mon: 'Monday',
        tue: 'Tuesday',
        wed: 'Wednesday',
        thu: 'Thursday',
        fri: 'Friday',
        sat: 'Saturday',
        sun: 'Sunday',
      },
    },
    quickMove: {
      title: 'Quick Operation',
      quickMoveOpr: 'Assign Shortcuts',
      funLancodeDis: 'Function Node Name',
      funCode: 'Function Node Number',
      authFunImg: 'Icon',
      AssImg: 'Atrribute Icon',
      pmtypeCodeDis: 'Please enter the name of the function node',
      errReminder: 'Can only select up to 6 nodes',
      set: 'Setting'
    },
    attendance:{
      title: 'Attendance of the day',
      sign: 'The sign in',
      leave: 'Leave of the day',
      Business: 'Business trip on the same day',
    },
    Staff:{
      title: 'Employees move',
      tmonth: 'Entry this month',
      member: 'Become a full member of this month',
      renew: 'This month to renew',
      mobilize: 'This month to mobilize',
      departure:'This month’s departure'
    },
    Employee:{
      title: 'Employee analysis',
      Gender: 'Gender analysis',
      Compilation: 'Compilation analysis',
      Age: 'Age analysis',
      Education: 'Education analysis',
    },
    Statistics:{
      title: 'User statistics',
      userNumber: 'Total number of users',
      Currently: 'Currently in force',
      effective: 'To be effective',
      newToday: 'New today',
      currentFailure :'Current failure'
    },
    mailMsg: {
      title: 'Mail Information',
      view: 'view',
      mailTime: 'Send Time',
      mailObject: 'Topic',
      mailTo: 'Receiver',
      mailCc: 'Writer',
      mailStatus: 'Status',
      mailContent: 'Mail Content',
      mailError: 'Error Message',
      mailDatasource: 'Data Resource',
      comment: 'Comment',
      mailTimeDis: 'Select start time',
      mailEtimeDis: 'Select end time',
      mailObjectDis: 'Please enter topic...',
      mailContentDis: 'Please enter mail content...',
      mailStatusDis: 'Please enter mail status...',
    },
    question: {
      title: 'Feedback',
      waitFeedback: 'Waiting for feedback',
      dayAdd: 'Added today',
      dayDeal: 'Dealing with today',
    },
    employee: {
      title: 'Business Analysis',
      currentEmp: 'Current Employee',
      monenEmp: 'Monthly Entry',
      monlevEmp: 'Monthly Leave',
      monzhEmp: 'Monthly Positive',
      sexRate: 'Sex Rate',
      man: 'Man',
      woman: 'Woman',
      education: 'Education',
      education1: 'CO',
      education2: 'BS',
      education3: 'MS',
      education4: 'PD',
    },
    bookStore: {
      title: 'Knowledge Base',
      tagTitle: 'System Knowledge Base',
      effectDate: 'Effective Date',
      back: 'Return to superior',
      attM: 'Attachment',
      cmutKntypeName: 'All Knowledge Bases',
      keyWordsDis: 'Please enter the knowledge base keyword...',
    },
    tools: {
      title: 'Small Tools',
      TaxCal: 'Tax Calculator',
      SocPolicy: 'Social Policy',
      OprBook: 'Operation Booklet',
      mostLink: 'Most Used Link',
    },
    contentList: {
      title: 'Business Contact',
      modaTitle: 'Business support',
      platSerConperson: 'Contacts',
      platSerTeam: 'Service Team',
      platSerTime: 'Service Time',
      platSerRange: 'Service Range',
      platSerLevelName: 'Service Level',
      platSerTel: 'Contact phone',
      platSerEmail: 'E-mail',
    },
    messageList: {
      title: 'Message Notice',
      allMessage: 'All Messages',
      unread: 'Unread message',
      readed: 'Read message',
      noticbaseTitle: 'Title',
      noticbaseSource: 'Type',
      noticbasePublish: 'Date',
      backTitle: 'Return to superior',
      attM: 'Attachment',
    },
    menuItem: {
      iquestion: 'Online consult',
      businessupport: 'Business support',
      platsetting: 'personalized setting',
      skinpeeler:'Skin peeler'
    },
    skinpeelers:{
      current:'Current use',
      immediately:'Skin peeling',
      classic:'Classic style',
      black: 'Black style',
      blue:'Blue style',
      green:'Green style',
      Navyblue:'Navy blue style',
      red: 'Red style',
      Deeppurple: 'Deep purple style' 
    },
    attendanceData:{
      title:'Attendance data',
      clock:'Attendance clock in record',
      replacement:'Employee card replacement application',
    },
    Personnel:{
      title:'Personnel affairs',
      self:'Work report and self-evaluation',
      information:'Mobilization of information confirmation',
      Renewal:'Renewal information confirmation',
      resignation:'Confirmation of resignation information',
    },
    Holiday:{
      title:'Holiday management',
      Leave:'Leave application',
      business:'Application for business trip',
      cancellation:'Application for leave cancellation',
      trip:'Business trip change',
      revoke:'Cancellation of business trip'
    },
    email: {
      // title: 'Mail Statistics',
      title: 'My Email',
      failtoday: 'Today\'s failure number',
      failcount: 'total number of failed failures',
      weekcount: 'Total number sent this week',
    },
    sms: {
      title: 'SMS statistics',
      failtoday: 'Today\'s failure number',
      failcount: 'total number of failed failures',
      weekcount: 'Total number sent this week',
      tiao: 'bar',
    },
    workno: {
      title: 'Employee number & job number monitoring',
      empIdnum: 'remaining employee number',
      postIdnum: 'remaining job number',
    },
    autotask: {
      title: 'automatic task statistics',
      count: 'total number of tasks',
      countstat: 'Total task count',
      validity: 'effective task number',
      invalid: 'number of failed tasks',
      typestat: 'Task category statistics',
      plstat: 'Task execution frequency statistics',
    },
    autotaskrun: {
      title: 'automatic task execution statistics',
      title1: 'Task running statistics',
      runfailure: 'Running today failed',
      runsuccess: 'Run today is successful',
      startfailure: 'Today failed to start',
      startsuccess: 'Today started successfully',
    },
    platSetting: {
      title: 'Platform seting',
      platApvset: 'My approval Settings',
      apMethod: 'Set the approval mode.',
      apMethodDis: 'Please select the mode of approval setting',
      setSuccess: 'Set up the success',
      noEmpleeRemind: 'The current user does not bind employees, please bind employees first!',
      grid: 'Sudoku Display Mode'
    },
    myMessage:{
      title:'My information',
      empTip:'The basic information',
      empNumber:'Work numgber',
      empName:'The name',
      empStatus:'State employees',
      empCompany:'The company',
      empDepart:'Department',
      empPost:'Post',
      empPLeve:'Job level',
      empEntime:'Entry time',
      empSiling:'Length of service',
      empTjobtime:'Working hours',
      whetherRemote:'Whether to enjoy the benefits of remote dispatch',
      whetherForeign:'Whether to enjoy the benefits of foreign introduction',
      officeMessage:'As the information',
      contractMessage:'The contract information',
      bankMessage:'The bank information',
      qualificaMessage:'The education information',
      trackRecord:'Work history',
      contactMessage:'Contact information',
      addressMessage:'Address information',
      familyMessage:'Family information',
    },
  },
}
