export default {
  'zh-CN': {
    // 社保险种调整
    socsecInsChg: {
      title: '险种调整台账',
      title1: '政策调整台账',
      chgStatus: '状态',
      startMonth: '调整生效起始月份',
      p_startMonth: '请选择调整生效起始月份',
      endMonth: '调整生效结束月份',
      p_endMonth: '请输入调整生效结束月份',
      chgSource: '调整来源',
      insurance: '险种',
      p_insurance: '请选择社保险种',
      p_empNoAndName: '请输入员工工号或者姓名',
      empNo: '员工工号',
      empName: '姓名',
      appMonth: '申请报增月份',
      effectiveMonth: '调整生效月份',
      chgReason: '调整原因',
      socpolicy: '社保政策',
      accpolicy: '公积金政策',
      chgType: '调整类别',
      oldBase: '原基数',
      newBase: '新基数',
      oldCompRio: '原公司缴纳比例(%)',
      newCompRio: '新公司缴纳比例(%)',
      oldCompPay: '原公司缴纳金额',
      newCompPay: '新公司缴纳金额',
      oldPerRio: '原个人缴纳比例(%)',
      newPerRio: '新个人缴纳比例(%)',
      oldPerPay: '原个人缴纳金额',
      newPerPay: '新个人缴纳金额',
      oldCompExPay: '原公司附加金额',
      newCompExPay: '新公司附加金额',
      oldPerExPay: '原个人附加金额',
      newPerExPay: '新个人附加金额',
      oldComp: '原公司',
      newComp: '新公司',
      oldLoc: '原社保缴纳地',
      newLoc: '新社保缴纳地',
      oldLoc1: '原公积金缴纳地',
      newLoc1: '新公积金缴纳地',
      oldPolicy: '原社保政策',
      newPolicy: '新社保政策',
      oldPolicy1: '原公积金政策',
      newPolicy1: '新公积金政策',
      ifAuto: '自动报增报减',
      newBaseRule: '新基数规则',
      newBaseIsSame: '新基数是否相同',
      newBaseAmount: '新社保基数',
      newBaseAmount1: '新公积金基数',
    },
  },
  'en-US': {
    socsecInsChg: {
      title: 'Insurance Chg Report',
      chgStatus: 'Status',
      startMonth: 'Effc Start Month',
      p_startMonth: 'Please select the EffcMonth',
      endMonth: 'Effc End Month',
      p_endMonth: 'Please select the Month',
      chgSource: 'Data Source',
      insurance: 'Insurance',
      p_insurance: 'Please select the insurance',
      p_empNoAndName: 'Please Input the Emp No. or Name',
      empNo: 'Employee No.',
      empName: 'Name',
      appMonth: 'Application Month',
      effectiveMonth: 'Chage Month',
      chgReason: 'Change Reason',
      policy: 'Policy',
      chgType: 'Change Type',
      oldBase: 'Pre Base',
      newBase: 'Chg base',
      oldCompRio: 'Pre Comp Rio(%)',
      newCompRio: 'Chg Comp Rio(%)',
      oldCompPay: 'Pre Comp Amount',
      newCompPay: 'Chg Comp Amount',
      oldPerRio: 'Pre Per Rio(%)',
      newPerRio: 'Chg Per Rio(%)',
      oldPerPay: 'Pre Per Amount',
      newPerPay: 'Chg Per Amount',
      oldCompExPay: 'Pre Comp Ex-Amount',
      newCompExPay: 'Chg Per Ex-Amount',
      oldPerExPay: 'Pre Per Ex-Amount',
      newPerExPay: 'Chg Per Ex-Amount',
      oldComp: 'Old Comp',
      newComp: 'New Comp',
      oldLoc: 'Old Location',
      newLoc: 'New Location',
      oldLoc1: 'Old Location',
      newLoc1: 'New Location',
      oldPolicy: 'Old Policy',
      newPolicy: 'New Policy',
      oldPolicy1: 'Old Policy',
      newPolicy1: 'New Policy',
      ifAuto: 'Is Auto',
      newBaseRule: 'New Base Rule',
      newBaseIsSame: 'Is new Base Same',
      newBaseAmount: 'Base Amount',
      newBaseAmount1: 'Base Amount',
    },
  },
}
