export default {
    'zh-CN': {
      fileClass: {
        title: '绩效目标定义',
        title1: '招聘面试通知',
        title2: '招聘渠道管理',
        title3: '面试待办事项',
        title4: '面试管理',
        title5: '面试通知',
        title6: '面试小组管理',
        title7: '面试官管理',
        title8: '面试调查结果',

      },
      inputPlaceholder: {
        inputholderSex: '请选择性别',
        inputholderOld: '请选择年龄',
        inputholderRecord: '请选择学历',
        inputholderMajor: '请输入专业',
        inputholderYear: '请选择工作年限',
        inputholderDatabase: '请选择是否仅简历库',
        inputholderChannelType: '请选择招聘渠道类型',
        inputholderChannelName: '请输入招聘渠道名称',
        inputholderLocation: '请输入公司地址',
        inputholderProvince: '请输入公司所在省份',

        inputholderChargingType: '请输入收费条目',
        inputholderChargingAccount: '请输入收费标准',
        inputholderChannelRemark: '请填写备注',

        inputholderNeedMessage: '缺少信息',

        inputholderContractName: '请输入联系人',

        inputholderContractName: '请输入请输入联系人',
        inputholderChannelName: '请输入招聘渠道名称',
        inputholderChannelType: '请输入招聘渠道类型',
        inputholderChannelProvince: '请输入公司所在省份',
        inputholderChannelLocation: '请输入公司地址',
        inputholderContractName: '请输入联系人',
        inputholderContractPhone: '请输入联系电话',
        inputholderContractEmail: '请输入联系人邮箱',
        inputholderContractWeixin: '请输入联系人微信',
        inputholderContractBusiness: '请输入业务领域',
        inputholderChannelIfcooperDis: '请输入是否合作',
        inputholderJinxing: '请输入是否进行',
        inputholderContractWeixinflag: '请上传微信二维码',

        activeCode: '请输入活动编号',
        activeName: '请输入活动名称',
        noticeComp: '请输入需求公司',
        noticeDept: '请输入需求部门',
        noticePosition: '请输入需求岗位',
        noticeName: '请输入应聘者姓名',
        noticeSex: '请输入应聘者性别',
        noticeIdtype: '请输入证件类型',
        noticeIdno: '请输入证件号',
        contractOld: '请输入年龄',
        noticeBirthday: '请输入出生日期',
        contractYear: '请输入工作年限',
        noticeHighestedu: '请输入最高学历',
        contractMajor: '请输入专业',
        noticeRound: '请输入当前轮次',
        noticeRemark3: '请输入最终面试结果',
        channelIfcooper: '请选择是否合作',
        noticePhone: '请输入手机号',
        noticeFwdate: '请输入参加工作日期',
        noticeStatus: '请输入求职状态',

      },
      table: {
        noticeCode: '活动单号',
        noticeIfcommit: '是否发送通知',
        noticeTime: '发送时间',
        noticeIfrequest: '是否已响应',
        noticeIntertime: '通知面试时间',
        noticePlace: '简历位置',
        rowName: '简历匹配度',      //
        noticeComp: '需求公司',
        noticeDept: '需求部门',
        noticePosition: '需求岗位',
        noticeName: '应聘者姓名',
        noticeSex: '应聘者性别',
        noticeIdtype: '证件类型',
        noticeIdno: '证件号码',
        noticeBirthday: '出生日期',
        noticeFwdate: '参加工作日期',
        noticePhone: '手机号',
        noticeEmail: '邮箱',
        noticeStatus: '求职状态',
        noticeLocation: '所在地',
        noticeHighestedu: '最高学历',
        noticeSbjname: '学科名称',
        noticeMarstatus: '婚姻状况',
        noticeNativeplace: '籍贯',
        noticePolitical: '政治面貌',
        noticeNation: '民族',
        noticeRuechannel: '简历渠道',
        noticeRuetype: '简历类别',
        noticeDesposition: '期望职位',
        noticeDescity: '期望城市',
        noticeDesmpay: '期望月薪',
        noticeRemark: '备注',
        noticeRound: '当前轮次',
        noticeIfprocee: '是否进行',
        noticeRemark3: '最终面试结果',
        activeCode: '活动编号',
        activeName: '活动名称',
        contractOld: '年龄',
        contractYear: '工作年限',
        noticeFwdate: '参加工作日期',
        contractMajor: '专业',

        channelType: '招聘渠道类型',
        channelName: '招聘渠道名称',
        channelProvince: '公司所在省份',
        channelLocation: '公司地址',
        channelIfcooper: '是否合作',
        channelRemark: '备注',

        chargingType: '收费条目',
        chargingAccount: '收费标准',
        channelOpr: '操作',

        contractName: '联系人',
        contractPhone: '联系电话',
        contractEmail: '联系人邮箱',
        contractWeixin: '联系人微信',
        contractBusiness: '业务领域',
        channelProvince: '公司所在省份',
        channelLocation: '公司地址',
        channelIfcooperDis: '是否合作',
        contractWeixinflag: '上传微信二维码',
        contractRemark: '备注',

      },
      reminder:{
        update: '请先修改数据'
      }
    },
    'en-US': {
      fileClass: {
        title: 'Definition of Performance Objectives',
        title1: 'Recruitment Interview Notice',
        title2: 'Recruitment Channel Management',
        title3: 'Interview to-do items',
        title4: 'Interview management',
        title5: 'Interview notice',
        title6: 'Interview group management',
        title7: 'Interviewer management',
        title8: 'Interview survey results',
      },
      inputPlaceholder: {
        inputholderSex: 'Please choose gender',
        inputholderOld: 'Please choose your age',
        inputholderRecord: 'Please choose your educational background',
        inputholderMajor: 'Please enter your major',
        inputholderYear: 'Please choose your working life',
        inputholderDatabase: 'Please choose whether or not the resume library is the only one',
        inputholderChannelType: 'Please choose the type of recruitment channel',
        inputholderChannelName: 'Please enter the name of the recruitment channel',
        inputholderLocation: 'Please enter the company address',
        inputholderProvince: 'Please enter the province where the company is located',

        inputholderChargingType: 'Please enter a fee entry',
        inputholderChargingAccount: 'Please enter the fee rate',
        inputholderChannelRemark: 'Please fill in the notes',

        inputholderNeedMessage: 'Lack of information',

        inputholderContractName: 'Please enter a contact',

        inputholderContractName: 'Please enter your contact number',
        inputholderChannelName: 'Please enter the name of the recruitment channel',
        inputholderChannelType: 'Please enter the type of recruitment channel',
        inputholderChannelProvince: 'Please enter the province where the company is located',
        inputholderChannelLocation: 'Please enter the company address',
        inputholderContractName: 'Please enter a contact',
        inputholderContractPhone: 'Please enter a contact number',
        inputholderContractEmail: 'Please enter your contact email',
        inputholderContractWeixin: 'Please enter a contact tweet',
        inputholderContractBusiness: 'Please enter business domain',
        inputholderChannelIfcooperDis: 'Please enter whether to cooperate or not',
        inputholderJinxing: 'Please enter whether to proceed or not',
        inputholderContractWeixinflag: 'Please upload tweet two-dimensional code',

        activeCode: 'Please enter the activity number',
        activeName: 'Please enter the activity name',
        noticeComp: 'Please enter Demand Company',
        noticeDept: 'Please enter the demand department',
        noticePosition: 'Please enter the required position',
        noticeName: 'Please enter the name of the applicant',
        noticeSex: 'Please enter the applicant`s gender',
        noticeIdtype: 'Please enter the Document type',
        noticeIdno: 'Please enter the Identification Number',
        contractOld: 'Please enter age',
        noticeBirthday: 'Please enter the date of birth',
        contractYear: 'Please enter the working life',
        noticeHighestedu: 'Please enter the highest educational background',
        contractMajor: 'Please enter your majo',
        noticeRound: 'Please enter the current round',
        noticeRemark3: 'Please enter the final interview results',
        channelIfcooper: 'Please choose whether to cooperate or not',

      },
      table: {
        noticeCode: 'Activity odd number',
        noticeIfcommit: 'Whether to send notification or not',
        noticeTime: 'Sending time',
        noticeIfrequest: 'Have you responded',
        noticeIntertime: 'Notify the interview time',
        noticePlace: 'Resume location',
        rowName: 'Resume Matching',
        noticeComp: 'Demand company',
        noticeDept: 'Demand Department',
        noticePosition: 'Demand post',
        noticeName: 'Candidate Name',
        noticeSex: 'Gender of applicants',
        noticeIdtype: 'Document type',
        noticeIdno: 'Identification Number',
        noticeBirthday: 'Date of birth',
        noticeFwdate: 'Date of participation',
        noticePhone: 'Cell-phone number',
        noticeEmail: 'mailbox',
        noticeStatus: 'Job hunting status',
        noticeLocation: 'Location',
        noticeHighestedu: 'Highest academic qualifications',
        noticeSbjname: 'Subject name',
        noticeMarstatus: 'Marital status',
        noticeNativeplace: 'Native place',
        noticePolitical: 'Political outlook',
        noticeNation: 'Nation',
        noticeRuechannel: 'Resume channel',
        noticeRuetype: 'Resume categories',
        noticeDesposition: 'Desired position',
        noticeDescity: 'Expectant City',
        noticeDesmpay: 'Expected salary',
        noticeRemark: 'Remarks',
        noticeRound: 'Current rotation',
        noticeIfprocee: 'Whether to proceed',
        noticeRemark3: 'Final interview results',
        activeCode: 'Activity number',
        activeName: 'Activity name',
        contractOld: 'Age',
        contractYear: 'Working life',
        noticeFwdate: 'Date of participation',
        contractMajor: 'major',

        channelType: 'Recruitment Channel Types',
        channelName: 'Name of Recruitment Channel',
        channelProvince: 'The province where the company is located',
        channelLocation: 'Company address',
        channelIfcooper: 'Cooperation',
        channelRemark: 'Remarks',

        chargingType: 'Charges entry',
        chargingAccount: 'Charging standard',
        channelOpr: 'operation',

        contractName: 'Contacts',
        contractPhone: 'Contact number',
        contractEmail: 'Contact mailbox',
        contractWeixin: 'Contact Wechat',
        contractBusiness: 'Business area',
        channelProvince: 'The province where the company is located',
        channelLocation: 'Company address',
        channelIfcooperDis: 'Cooperation',
        contractWeixinflag: 'Upload TWO-DIMENSIONAL CODE',
        contractRemark: 'Remarks',

      },
      reminder:{
        update: 'Please modify the data first',
      }
    },
  }
