export default {
    'zh-CN': {
      fileClass: {
        title: '绩效目标定义',
        title1: '考核对象设置',
        title2: '组织绩效方案',
        title3: '组织考核面谈',
        evatCode: '编码',
        evatYear: '年度',
        evatName: '目标名称',
        evatNormDis: '关联指标',
        evatAmout: '目标额度(两位小数)',
        evatDesc: '目标说明',
        evatLevelDis: '分解层级',
        evatWeight: '权重',
        claNote: '备注',
        evatExplain: '指标分解',
        checkTemplet: '考核模板',
        checkPlan: '考核方案',
        checkObj: '考核对象',
        evaacCode: '活动编号',
        evaacMethod: '考核方法',
        operate: '操作',
        release: '发布',
        change: '修改',
        evaacIsself: '是否自评',
        evaacName: '活动名称',
        btn1: '绩效目标',
        btn2: '考评人',
        btn3: '确定',
        checkStaff: '被考核员工',
        checkCompany: '公司',
        checkSection: '部门',
        checkStation: '岗位',
        goal: '指标',
        doneGoal: '目标值',
        interviewDetail: '面谈详情',
        summaryActive: '考核活动',
        summaryCycle: '考核周期',
        summaryAll: '考核人总数',
        summaryAllFinish: '已完成考核人数',
        summaryProgress: '考核进度',
        summaryScore: '平均成绩',
        summaryResult: '考核结果',
        summaryStatus: '状态',
      },
      inputPlaceholder: {
        inputholderYear: '请输入年份',
        inputholderName: '请输入目标名称',
        evatCode: '请输入编码',
        evatYear: '请选择年份',
        evatName: '请输入目标名称',
        evatNormDis: '请选择关联指标',
        evatAmout: '请输入目标额度(两位小数)',
        evatDesc: '请输入目标说明',
        evatLevelDis: '请输入分解层级',
        evatWeight: '请输入权重',
        claNote: '请输入备注',
        checkTemplet: '请选择考核活动',
        evaacCode: '请输入活动编号',
        evaacName: '请输入活动名称',
        checkPlan: '请选择考核方案',
        evaacMethod: '请选择考核方法',
        evaacIsself: '请选择是否自评',
        doneGoal: '请输入目标值',
      },
      explain:{
        explain: '考核目标分解',
        norm: '指标',
        mount: '目标额度',
      },
      reminder:{
          update: '请先修改数据'
      }
    },
    'en-US': {
      fileClass: {
        title: 'Organize Goal Management',
        title1: 'Organize Activity Management',
        title2: 'Organize Program Management',
        evatCode: 'Code',
        evatYear: 'year',
        evatName: 'Target name',
        evatNormDis: 'Correlation index',
        evatAmout: 'Target quota (two decimal digits)',
        evatDesc: 'Target specification',
        evatLevelDis: 'Decomposition hierarchy',
        evatWeight: 'weight',
        claNote: 'Remarks',
        evatExplain: 'Index decomposition',
        inputholderYear: 'Please enter the year',
        inputholderName: 'Please enter the target name',
        checkTemplet: 'Please select the assessment activity',
        checkPlan: 'Assessment plan',
        checkObj: 'Object of assessment',
        evaacCode: 'Activity number',
        evaacMethod: 'Assessment method',
        operate: 'operation',
        release: 'Release',
        change: 'modify',
        evaacIsself: 'Self evaluation',
        evaacName: 'Activity name',
        btn1: 'Organize goal',
        btn2: 'Examiner',
        btn3: 'Sure',
        checkStaff: 'Assessed Employees',
        checkCompany: 'company',
        checkSection: 'department',
        checkStation: 'post',
        goal: 'index',
        doneGoal: 'target value',
      },
      inputPlaceholder: {
        inputholderYear: 'Please enter the year',
        inputholderName: 'Please enter the target name',
        evatCode: 'Please, enter the code',
        evatYear: 'Please choose the year',
        evatName: 'Please enter the target name',
        evatNormDis: 'Please select the relevant indicators',
        evatAmout: 'Please enter the target quota (two decimal digits)',
        evatDesc: 'Please enter the target description',
        evatLevelDis: 'Please enter the decomposition hierarchy',
        evatWeight: 'Please enter weight',
        claNote: 'Please enter notes',
        checkTemplet: 'Please select the assessment template',
      },
      explain:{
        explain: 'Decomposition of Assessment Objectives',
        norm: 'index',
        mount: 'Target quota',
      },
      reminder:{
          update: 'Please modify the data first',
      }
    },
  }
