export default {
    'zh-CN': {
      fileClass: {
        title: '员工考核记录',
        titleTeam: '组织考核记录',
        title1: '绩效考核详情',
        title2: '绩效指标评分',
        columnsActive: '考核活动',
        columnsCompany: '公司',
        columnsDepartment: '部门',
        columnStation: '岗位',
        columnsObj: '考核对象',
        columnsScore: '考核评分',
        columnsProgress: '考核进度',
        performanceDetail: '考评详情',
        performanceScore: '查看指标评分',
        activeCode: '编码',
        evaacEmpidsDis: '被考核员工',
        checkMan: '考核人',
        checkManType: '考核人类型',
      },
      inputPlaceholder: {
        searchActive: '请输入考核活动',
        searchObj: '请输入被考核对象',
        searchCompany: '请选择公司',
      },
    },
    'en-US': {
        fileClass: {
            title: 'Performance Record Management',
            titleTeam: 'Performance TeamRecord Management',
            title1: 'Details of performance appraisal',
            title2: 'Performance Indicator Scoring',
            columnsActive: 'Assessment activities',
            columnsCompany: 'company',
            columnsDepartment: 'department',
            columnStation: 'post',
            columnsObj: 'Object of assessment',
            columnsScore: 'Assessment score',
            columnsProgress: 'Assessment progress',
            performanceDetail: 'Assessment progress',
            performanceScore: 'View Indicator Score',
            activeCode: 'Code',
            evaacEmpidsDis: 'Assessed Employees',
            checkMan: 'Assessor',
            checkManType: 'Assessment of human type',
          },
          inputPlaceholder: {
            searchActive: 'Please enter the assessment activities',
            searchObj: 'Please enter the object to be assessed',
            searchCompany: 'Please choose the company',
          },
    },
  }
